#配置端口
server:
  port: 8080
#  port: 9999

# 配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# 配置SQL打印
#logging:
#  level:
#    com.example.demo.test.mapper : debug